
spring:
  profiles:
    active: dev
---
server:
  port: 8025
spring:
  application:
    profiles: dev
    name: springcloud-provider-dept
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
---

server:
  port: 8026
spring:
  application:
    profiles: test
    name: springcloud-provider-dept
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka