
spring:
  profiles:
    active: dev
---

server:
  port: 8025
spring:
  application:
    name: springcloud-provider-dept
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
---
server:
  port: 8026
spring:
  application:
    name: springcloud-provider-dept
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka